<div class="feed-block">
    <?php if (!empty($block['resources'])) { ?>
        <div class="feed-list clearfix">
            <?php foreach ($block['resources'] as $feed) { ?>
                <div class="feed-single clearfix h-feed">
                    <div class="feed-single-title p-name">
                        <h3 class="clearfix" itemprop="headline">
                            <?php if ($block['link-type'] == 'external') { ?>
                                <a target="_blank" rel="nofollow" title="<?php echo $this->escape($feed['title']); ?>"
                                   href="<?php echo $this->escape($feed['link']); ?>">
                                    <?php echo $this->escape($feed['title']); ?>
                                </a>
                            <?php } else { ?>
                                <a title="<?php echo $this->escape($feed['title']); ?>"
                                   href="<?php echo $this->escape($feed['feedUrl']); ?>">
                                    <?php echo $this->escape($feed['title']); ?>
                                </a>
                            <?php } ?>
                        </h3>
                    </div>
                    <div class="feed-single-information small">
                        <ul class="clearfix list-inline">
                            <?php if ($block['show-source']) { ?>
                                <li><i class="fa fa-rss"></i> <?php echo $this->escape($feed['sourceTitle']); ?></li>
                            <?php } ?>
                            <?php if ($block['show-time']) { ?>
                                <li><i class="fa fa-clock-o"></i> <?php echo $this->escape($feed['time_create_view']); ?></li>
                            <?php } ?>
                            <?php if ($block['show-hits']) { ?>
                                <li><i class="fa fa-eye"></i> <?php echo $this->escape(_number($feed['hits'])); ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <?php if ($block['show-description'] && !empty($feed['description'])) { ?>
                        <div class="feed-single-summery clearfix p-summary">
                            <?php echo $feed['description']; ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
</div>