<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header clearfix">
        <h1><?php _e('List of feeds'); ?></h1>
    </div>
    <?php if (!empty($config['text_description_index']) && isset($page) && $page == 1) { ?>
        <div class="well feed-description">
            <?php echo $config['text_description_index']; ?>
        </div>
    <?php } ?>
    <?php if (!empty($feeds)) { ?>
        <div class="feed-list clearfix">
            <?php foreach ($feeds as $feed) { ?>
                <div class="feed-single clearfix h-feed">
                    <div class="feed-single-title p-name">
                        <h2 class="clearfix" itemprop="headline">
                            <a itemprop="url" title="<?php echo $this->escape($feed['title']); ?>"
                               href="<?php echo $this->escape($feed['feedUrl']); ?>">
                                <?php echo $this->escape($feed['title']); ?>
                            </a>
                        </h2>
                    </div>
                    <div class="feed-single-information small">
                        <ul class="clearfix list-inline feed-time">
                            <li><i class="fa fa-rss"></i> <?php echo $this->escape($feed['sourceTitle']); ?></li>
                            <li><i class="fa fa-clock-o"></i> <?php echo $this->escape($feed['time_create_view']); ?></li>
                            <li><i class="fa fa-eye"></i> <?php echo $this->escape(_number($feed['hits'])); ?></li>
                        </ul>
                    </div>
                    <div class="feed-single-summery clearfix p-summary">
                        <?php echo $feed['description']; ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>